version: '3'
tasks:
  scan-image:
    desc: "Scan a Docker image for vulnerabilities using Trivy"
    cmds:
      - docker run aquasec/trivy image --format json --output result.json python:3.4-alpine
