version: '3'
tasks:
  depcheck-scan:
    desc: "run dependency check"
    cmds:
      - docker run -v $(pwd)/spring-petclinic:/tmp/spring-petclinic --rm -it owasp/dependency-check --format json --project "petclinic" --scan /tmp/spring-petclinic/target/petclinic.jar
